mutation CreateMovieReview($input: CreateMovieReviewInput!) {
  createMovieReview(input: $input) {
    movieReview {
      id
      title
      body
      rating
      movieByMovieId {
        id
        title
        userByUserCreatorId {
          id
          name
        }
      }
      userByUserReviewerId {
        id
        name
      }
      commentsByMovieReviewId {
        nodes {
          id
          title
          body
          userByUserId {
            id
            name
          }
        }
      }
    }
  }
}
